[server]
fileWatcherType = "none"

[theme]
base = "light"
primaryColor = "#d4a373"  # Warm neutral
backgroundColor = "#fdfaf6"  # Soft off-white
secondaryBackgroundColor = "#ffffffee"  # Slightly translucent white
textColor = "#1c1c1c"  # Rich gray
font = "sans serif"


