[server]
fileWatcherType = "none"

[theme]
base = "light"  # or "dark"
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"  # Options: "sans serif", "serif", "monospace"
