[server]
fileWatcherType = "none"

[theme]
base = "light"
layout = "wide"
primaryColor = "#f5f5f5"  # Warm neutral
backgroundColor = "#fefefe"  # Soft off-white
secondaryBackgroundColor = "#ffffffee"  # Slightly translucent white
textColor = "#000000"  # Black for clear readability
font = "sans serif"
