[server]
fileWatcherType = "none"

[theme]
base = "light"
primaryColor = "#f5f5f5"  # Warm neutral
backgroundColor = "rgb(245,245,245)"  # Soft off-white
secondaryBackgroundColor = "#ffffffee"  # Slightly translucent white
textColor = "#1c1c1c"  # Rich gray
font = "sans serif"


